
[router]
kpc-edge-router ansible_host=172.20.20.7

[spine]
kpc-spine-l3-1 ansible_host=172.20.20.11
kpc-spine-l3-2 ansible_host=172.20.20.2

[leaf]
kpc-leaf-l3-1 ansible_host=172.20.20.3
kpc-leaf-l3-2 ansible_host=172.20.20.10
kpc-leaf-l3-3 ansible_host=172.20.20.4
kpc-leaf-l3-4 ansible_host=172.20.20.6

