[spine]
spine1 ansible_host = #Please management IP
spine2 ansible_host = #Please management IP

[leaf]
leaf1 ansible_host = #Please management IP
leaf2 ansible_host = #Please management IP
leaf3 ansible_host = #Please management IP
leaf4 ansible_host = #Please management IP

