---

- name: All Device Configuration
  hosts: all

  vars_files:
  - creds/cred.yml

  tasks:
  - name: Banner configuration and OSPF Setup
    ansible.netcommon.cli_config:
      config: |
        configure terminal
        banner motd
        ---------------------Authorized Users Only!!!------------------------
        EOF

        router ospf 1
        area 0.0.0.0 default-cost 10
        auto-cost reference-bandwidth 10000

        write memory

        exit

- name: Leaf and Router Configuration
  hosts: leaf

  vars_files:
  - creds/cred.yml

  tasks:
  - name: Advertising networks for OSPF from eth1 and eth2
    ansible.netcommon.cli_config:
      config: |
        configure terminal

        interface vlan 10
        no shut
        ip ospf area 0.0.0.0

        interface Ethernet1-2
        ip ospf area 0.0.0.0
        ip ospf network point-to-point

        no ip route 0.0.0.0/0 172.20.20.1

        interface Ethernet23-24
        switchport mode access
        switchport access vlan 10

        write memory

        exit

- name: Spine Configuration
  hosts: spine

  vars_files:
  - creds/cred.yml

  tasks:
  - name: Advertising networks for OSPF from eth3-6, default route, and default information
    ansible.netcommon.cli_config:
      config: |
        configure terminal

        ip route 0.0.0.0/0 eth1

        interface Ethernet 3-6
        ip ospf area 0.0.0.0
        ip ospf network point-to-point

        router ospf 1
        default-information originate

        write memory

        exit

- name: Information Gathering and Verification
  hosts: spine1

  vars_files:
  - creds/cred.yml

  tasks:
  - name: Getting ip route information
    ansible.netcommon.cli_command:
      command: show ip route
    register: ip_route_info

  - name: Displaying IP route infromation
    debug:
      var: ip_route_info

  - name: Getting OSPF neighbor information
    ansible.netcommon.cli_command:
      command: show ip ospf neighbor summary
    register: ospf_neighbor

  - name: Displaying OSPF neighbor information
    debug:
      var: ospf_neighbor
...
